-- Lintu: shared requests and orders storage.
-- Admin access is granted only to users provisioned server-side with
-- app_metadata.role = 'admin'. Never set this claim from the browser.

create type public.request_status as enum (
  'Новая',
  'Отменена',
  'Заказ сформирован'
);

create type public.order_status as enum (
  'Принят',
  'В полёте',
  'Доставлен',
  'Отменён'
);

create table public.requests (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  name text not null,
  phone text not null,
  email text not null,
  status public.request_status not null default 'Новая'
);

create table public.orders (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  order_number bigint generated by default as identity not null unique,
  request_id uuid unique references public.requests(id) on delete set null,
  customer text not null,
  status public.order_status not null default 'Принят',
  delivery_date date not null,
  delivery_time time not null,
  from_address text not null,
  to_address text not null,
  weight_kg numeric(10, 2) not null check (weight_kg >= 0),
  price_rub integer not null check (price_rub >= 0)
);

create index requests_created_at_idx on public.requests (created_at desc);
create index requests_status_created_at_idx on public.requests (status, created_at desc);
create index orders_delivery_date_idx on public.orders (delivery_date desc, delivery_time desc);

create or replace function public.is_admin()
returns boolean
language sql
stable
set search_path = ''
as $$
  select coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin';
$$;

alter table public.requests enable row level security;
alter table public.orders enable row level security;

revoke all privileges on table public.requests from public, anon, authenticated;
revoke all privileges on table public.orders from public, anon, authenticated;
revoke all privileges on sequence public.orders_order_number_seq from public, anon, authenticated;

-- The public form can submit only its three fields. id, created_at and status
-- are all database-controlled; the policy also enforces the default status.
grant insert (name, phone, email) on table public.requests to anon;

grant select, insert, update, delete on table public.requests to authenticated;
grant select, insert, update, delete on table public.orders to authenticated;
grant usage on sequence public.orders_order_number_seq to authenticated;

revoke all on function public.is_admin() from public, anon;
grant execute on function public.is_admin() to authenticated;

create policy "anon can create new requests"
on public.requests
for insert
to anon
with check (status = 'Новая');

create policy "admins manage requests"
on public.requests
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "admins manage orders"
on public.orders
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

-- Creates an order and marks its source request as formed in one transaction.
-- The request_id unique constraint plus the status check prevent duplicates.
create or replace function public.create_order_from_request(
  p_request_id uuid,
  p_customer text,
  p_from_address text,
  p_to_address text,
  p_weight_kg numeric,
  p_price_rub integer,
  p_delivery_date date default current_date,
  p_delivery_time time default current_time
)
returns public.orders
language plpgsql
security invoker
set search_path = pg_catalog, public
as $$
declare
  created_order public.orders;
begin
  if not public.is_admin() then
    raise exception 'Admin role is required' using errcode = '42501';
  end if;

  update public.requests
  set status = 'Заказ сформирован'
  where id = p_request_id
    and status = 'Новая'
    and not exists (
      select 1
      from public.orders
      where request_id = p_request_id
    );

  if not found then
    raise exception 'Request is unavailable or already has an order' using errcode = 'P0001';
  end if;

  insert into public.orders (
    request_id,
    customer,
    status,
    delivery_date,
    delivery_time,
    from_address,
    to_address,
    weight_kg,
    price_rub
  )
  values (
    p_request_id,
    nullif(trim(p_customer), ''),
    'Принят',
    p_delivery_date,
    p_delivery_time,
    nullif(trim(p_from_address), ''),
    nullif(trim(p_to_address), ''),
    p_weight_kg,
    p_price_rub
  )
  returning * into created_order;

  return created_order;
end;
$$;

revoke all on function public.create_order_from_request(uuid, text, text, text, numeric, integer, date, time) from public, anon;
grant execute on function public.create_order_from_request(uuid, text, text, text, numeric, integer, date, time) to authenticated;

-- Clean, deterministic demo data. Existing browser localStorage data is not imported.
insert into public.requests (id, created_at, name, phone, email, status)
values
  ('a1000000-0000-4000-8000-000000000001', '2026-04-03 09:15:00+03', 'Екатерина Морозова', '+7 (900) 123-45-67', 'kate.m@mail.ru', 'Новая'),
  ('a1000000-0000-4000-8000-000000000002', '2026-04-09 14:40:00+03', 'Павел Новиков', '+7 (905) 765-43-21', 'p.novikov@gmail.com', 'Заказ сформирован'),
  ('a1000000-0000-4000-8000-000000000003', '2026-04-16 11:05:00+03', 'Виктория Лебедева', '+7 (911) 222-33-44', 'vika.l@yandex.ru', 'Отменена'),
  ('a1000000-0000-4000-8000-000000000004', '2026-04-24 16:20:00+03', 'Сергей Волков', '+7 (926) 555-66-77', 's.volkov@mail.ru', 'Заказ сформирован'),
  ('a1000000-0000-4000-8000-000000000005', '2026-04-30 10:35:00+03', 'Наталья Зайцева', '+7 (903) 888-99-00', 'n.zaytseva@gmail.com', 'Новая');

insert into public.orders (
  order_number,
  request_id,
  created_at,
  customer,
  status,
  delivery_date,
  delivery_time,
  from_address,
  to_address,
  weight_kg,
  price_rub
)
values
  (1041, 'a1000000-0000-4000-8000-000000000002', '2026-04-09 15:10:00+03', 'Павел Новиков', 'В полёте', '2026-04-19', '13:05', 'Ленинский пр-т, 45', 'ул. Арбат, 12', 0.60, 1200),
  (1042, 'a1000000-0000-4000-8000-000000000004', '2026-04-24 16:45:00+03', 'Сергей Волков', 'Принят', '2026-04-24', '17:10', 'Варшавское ш., 56', 'ул. Покровка, 18', 1.40, 1850),
  (1043, null, '2026-04-26 10:20:00+03', 'Анна Смирнова', 'Доставлен', '2026-04-26', '12:40', 'ул. Тверская, 10', 'Кутузовский пр-т, 24', 1.20, 1850),
  (1044, null, '2026-04-28 08:55:00+03', 'Мария Иванова', 'Отменён', '2026-04-28', '10:30', 'Пресненская наб., 8', 'ул. Маросейка, 6', 2.10, 2950);

select setval(pg_get_serial_sequence('public.orders', 'order_number'), 1044, true);
